### ISSUE TITLE
Syntax error in demo yamls (Actors)

### ISSUE THREAD

**Issue by brianfu** [microsoft/sca-fuzzer#103]
demo/detecting-mds.yaml and demo/detecting-foreshadow.yaml have this structure:
```yaml
# environment
actor:
  - name: "main"
  - data_properties:
    - accessed: False
```

When then should have this structure:
```yaml
# Actors
actors:
  - main:
    - data_properties:
      - present: true
```
